// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtbFZYZaNT9SlsdvlTgPZseosVDQmjH9M',
    appId: '1:556875955369:web:1af1d6d17c4b1ea1117db8',
    messagingSenderId: '556875955369',
    projectId: 'finance-tracker-ef330',
    authDomain: 'finance-tracker-ef330.firebaseapp.com',
    storageBucket: 'finance-tracker-ef330.firebasestorage.app',
    measurementId: 'G-NX4EQHRF2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEMeloRsugZsqPfjSKIcNOZjH16MtFLmQ',
    appId: '1:556875955369:android:9be64b567a748640117db8',
    messagingSenderId: '556875955369',
    projectId: 'finance-tracker-ef330',
    storageBucket: 'finance-tracker-ef330.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_36Qm4Shwiuae7HZ8omoppMNw_a0UAeA',
    appId: '1:556875955369:ios:132d5e54a06bcbb3117db8',
    messagingSenderId: '556875955369',
    projectId: 'finance-tracker-ef330',
    storageBucket: 'finance-tracker-ef330.firebasestorage.app',
    iosClientId: '556875955369-0f8b5a7t52c8dvijc4f76ope191i67qk.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_36Qm4Shwiuae7HZ8omoppMNw_a0UAeA',
    appId: '1:556875955369:ios:132d5e54a06bcbb3117db8',
    messagingSenderId: '556875955369',
    projectId: 'finance-tracker-ef330',
    storageBucket: 'finance-tracker-ef330.firebasestorage.app',
    iosClientId: '556875955369-0f8b5a7t52c8dvijc4f76ope191i67qk.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtbFZYZaNT9SlsdvlTgPZseosVDQmjH9M',
    appId: '1:556875955369:web:e1ea74746fb611f3117db8',
    messagingSenderId: '556875955369',
    projectId: 'finance-tracker-ef330',
    authDomain: 'finance-tracker-ef330.firebaseapp.com',
    storageBucket: 'finance-tracker-ef330.firebasestorage.app',
    measurementId: 'G-122SMPK163',
  );
}
